version: '3.8'

services:
  # 1. PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: onboarding_db
    restart: always
    environment:
      # These credentials should match your Django settings in a dev environment
      POSTGRES_DB: actserv
      POSTGRES_USER: mburu
      POSTGRES_PASSWORD: mburu
    ports:
      
      - "5432:5432"
    volumes:
      
      - postgres_data:/var/lib/postgresql/data/

  # 2. Django Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onboarding_backend
    restart: always
    depends_on:
      - db
  
    ports:
      - "8000:8000"
    environment:
     
      DATABASE_HOST: db         
      DATABASE_NAME: onboard_db
      DATABASE_USER: dev_user
      DATABASE_PASSWORD: dev_password
      SECRET_KEY: 'your-secure-development-key'
      DEBUG: 'True'
    volumes:

      - backend_media:/vol/web/media
      - backend_static:/vol/web/static
    

    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"


  
  frontend:
    build:
      context: ./frontend/user-interface
      dockerfile: Dockerfile
    container_name: onboarding_frontend
    restart: always
    
    ports:
      - "3000:80" 
    depends_on:
      - backend
    environment:
      
      REACT_APP_API_URL: http://localhost:8000/

# Define persistent volumes
volumes:
  postgres_data:
  backend_media:
  backend_static: