# Generated by Django 5.2.6 on 2025-09-29 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='conditional_field',
            field=models.ForeignKey(blank=True, help_text="The field (on the same form) that controls this field's visibility.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_fields', to='forms.field'),
        ),
        migrations.AddField(
            model_name='field',
            name='conditional_operator',
            field=models.CharField(blank=True, choices=[('equal_to', 'Equal To'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('not_equal_to', 'Not Equal To')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='conditional_value',
            field=models.CharField(blank=True, help_text="The threshold value (e.g., '50000' or 'true').", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='is_conditional',
            field=models.BooleanField(default=False, help_text="Set to True if this field's visibility depends on another field."),
        ),
    ]
